# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8002

spring:
  application:
    name: shard-provider-8002
  profiles:
    active: dev

# mybatis
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml